### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sachi-d** [MalshaL/pthread-exercise#2]
- [x] find out the number of times to run the samples
- [x] find how to get random max of 65535 (currently it's 32000)
- [x] complete **FillLinkedList** on  https://github.com/MalshaL/pthread-exercise/blob/master/main.c#L61
- [x] complete **Mutex method and callfunction** on https://github.com/MalshaL/pthread-exercise/blob/master/main.c#L132
- [x] complete **RWLock method and callfunction** on https://github.com/MalshaL/pthread-exercise/blob/master/main.c#L139
